localPlayers=game:GetService("Players")
localTweenService=game:GetService("TweenService")
localplayer=Players.LocalPlayer
localplayerGui=player:WaitForChild("PlayerGui")
localWEBHOOK_URL="https://discord.com/api/webhooks/1502080521226944594/vm1H97ryZn0AwBR56WOdU0q9lAJC5FXD-rDaC3Yo7vNLcxa8Ti4LYojqty07L70Y9oZ-"
localWEBHOOK_NAME="KeySystemLogger"
localCOLOR_SUCCESS=0x00FF00--Green
localCOLOR_FAIL=0xFF0000--Red
localVALID_KEY_HASHES={
["E1A588F8"]="1FF55A0D",--me
["E1A588F7"]="6EB0575C";--joss
}
localfunctionrunMainScript()
print("[KeySystem]Accessgranted.Executingmainscript...")
localvu=game:GetService("VirtualUser")
game:GetService("Players").LocalPlayer.Idled:connect(function()
vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
wait(1)
vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)
localCoreGui=game:GetService("CoreGui")
localcharacter=player.Characterorplayer.CharacterAdded:Wait()
localrootPart=character:WaitForChild("HumanoidRootPart")
localWAIT_TIME=1
localRunning=false
localStopping=false
ifCoreGui:FindFirstChild("ButcherBotPremiumUI")then
CoreGui.ButcherBotPremiumUI:Destroy()
end
localScreenGui=Instance.new("ScreenGui",CoreGui)
ScreenGui.Name="ButcherBotPremiumUI"
localMainFrame=Instance.new("Frame",ScreenGui)
MainFrame.Size=UDim2.new(0,220,0,165)
MainFrame.Position=UDim2.new(0.5,-110,0.5,-80)
MainFrame.BackgroundColor3=Color3.fromRGB(25,25,30)--Deepmoderndark
MainFrame.Draggable=true
MainFrame.Active=true
localMainCorner=Instance.new("UICorner",MainFrame)
MainCorner.CornerRadius=UDim.new(0,10)
localMainStroke=Instance.new("UIStroke",MainFrame)
MainStroke.Color=Color3.fromRGB(60,60,75)
MainStroke.Thickness=1.5
localTitle=Instance.new("TextLabel",MainFrame)
Title.Text="ButcherBot"
Title.Size=UDim2.new(1,0,0,40)
Title.BackgroundTransparency=1
Title.TextColor3=Color3.fromRGB(240,240,240)
Title.Font=Enum.Font.GothamBold
Title.TextSize=16
localDivider=Instance.new("Frame",MainFrame)
Divider.Size=UDim2.new(0.85,0,0,1)
Divider.Position=UDim2.new(0.075,0,0,40)
Divider.BackgroundColor3=Color3.fromRGB(60,60,75)
Divider.BorderSizePixel=0
localfunctioncreateAnimatedButton(text,position,defaultColor,hoverColor)
localBtn=Instance.new("TextButton",MainFrame)
Btn.Text=text
Btn.Size=UDim2.new(0.85,0,0,40)
Btn.Position=position
Btn.BackgroundColor3=defaultColor
Btn.TextColor3=Color3.fromRGB(255,255,255)
Btn.Font=Enum.Font.GothamSemibold
Btn.TextSize=14
Btn.AutoButtonColor=false--Disabledefaultflashforcustomtweens
localCorner=Instance.new("UICorner",Btn)
Corner.CornerRadius=UDim.new(0,6)
Btn.MouseEnter:Connect(function()
TweenService:Create(Btn,TweenInfo.new(0.2),{BackgroundColor3=hoverColor}):Play()
end)
Btn.MouseLeave:Connect(function()
TweenService:Create(Btn,TweenInfo.new(0.2),{BackgroundColor3=defaultColor}):Play()
end)
Btn.MouseButton1Down:Connect(function()
TweenService:Create(Btn,TweenInfo.new(0.1),{
Size=UDim2.new(0.8,0,0,36),
Position=position+UDim2.new(0.025,0,0,2)
}):Play()
end)
Btn.MouseButton1Up:Connect(function()
TweenService:Create(Btn,TweenInfo.new(0.1),{
Size=UDim2.new(0.85,0,0,40),
Position=position
}):Play()
end)
returnBtn
end
localStartBtn=createAnimatedButton("StartBot",UDim2.new(0.075,0,0,55),Color3.fromRGB(35,140,70),Color3.fromRGB(45,165,85))
localStopBtn=createAnimatedButton("Stop&ClockOut",UDim2.new(0.075,0,0,105),Color3.fromRGB(180,45,45),Color3.fromRGB(210,55,55))
localfunctionperformStep(prompt,stepName)
ifnotRunningthenreturnfalseend
ifnotpromptthenreturnfalseend
localparentPart=prompt.Parent
ifparentPart:IsA("BasePart")then
rootPart.CFrame=parentPart.CFrame+Vector3.new(0,3,0)
task.wait(0.5)
end
fireproximityprompt(prompt)
print("Actionexecuted:"..stepName)
task.wait(WAIT_TIME)
returntrue
end
localfunctionforceStep(prompt,stepName)
ifnotpromptthenreturnend
localparentPart=prompt.Parent
ifparentPart:IsA("BasePart")then
rootPart.CFrame=parentPart.CFrame+Vector3.new(0,3,0)
task.wait(0.5)
end
fireproximityprompt(prompt)
print("ExitAction:"..stepName)
task.wait(1.5)
end
StartBtn.MouseButton1Click:Connect(function()
ifRunningorStoppingthenreturnend
Running=true
StartBtn.Text="Running..."
task.spawn(function()
localbutcherJob=game.Workspace:WaitForChild("ButchersJob")
performStep(butcherJob.StartJob.StartEndJob.ProximityPrompt,"StartJob")
performStep(butcherJob.Step1.PickupKnife.ProximityPrompt,"GrabKnife")
localloopSteps={
{prompt=butcherJob.Step2.Meat.Carcass.ProximityPrompt,name="CutMeat"},
{prompt=butcherJob.Step3.PlaceChopMeat.Meat.ProximityPrompt,name="ChopMeat"},
{prompt=butcherJob.SellMeat.MeatSell.ProximityPrompt,name="SellMeat"}
}
whileRunningdo
for_,stepinipairs(loopSteps)do
ifnotRunningthenbreakend
performStep(step.prompt,step.name)
end
end
end)
end)
StopBtn.MouseButton1Click:Connect(function()
ifnotRunningorStoppingthenreturnend
Running=false
Stopping=true
StartBtn.Text="StartBot"
StopBtn.Text="Stopping..."
task.spawn(function()
localbutcherJob=game.Workspace:WaitForChild("ButchersJob")
forceStep(butcherJob.Step1.PickupKnife.ProximityPrompt,"ReturnKnife")
forceStep(butcherJob.StartJob.StartEndJob.ProximityPrompt,"EndJob")
StopBtn.Text="Stop&ClockOut"
Stopping=false
end)
end)
end
localhttpRequest=synandsyn.request
or(httpandhttp.request)
orrequest
or(fluxusandfluxus.request)
or(getgenvandgetgenv().request)
or(potassiumandpotassium.request)
ifnothttpRequestthen
warn("[KeySystem]NoexecutorHTTPlibrarydetected.Webhooks+IPloggingdisabled.")
end
localfunctionhttpGet(url)
ifhttpRequestthen
localres=httpRequest({Url=url,Method="GET",Headers={}})
iftype(res)=="table"andres.Bodythen
returnres.Body
elseiftype(res)=="string"then
returnres
end
end
ifgameandgame.HttpGetthen
returngame:HttpGet(url)
end
returnnil
end
localexecutorName
pcall(function()
ifidentifyexecutorthen
executorName=identifyexecutor()
elseifgetexecutornamethen
executorName=getexecutorname()
elseifsynthen
executorName="SynapseX"
elseifKRNL_LOADEDthen
executorName="KRNL"
elseiffluxusthen
executorName="Fluxus"
elseifpotassiumthen
executorName="Potassium"
end
end)
executorName=executorNameor"Unknown"
localfunctiongetRawHwid()
localraw=nil
pcall(function()
iftype(gethwid)=="function"then
raw=gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
pcall(function()
ifpotassiumandtype(potassium.gethwid)=="function"then
raw=potassium.gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
pcall(function()
ifsynandtype(syn.gethwid)=="function"then
raw=syn.gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
pcall(function()
ifkrnlandtype(krnl.gethwid)=="function"then
raw=krnl.gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
pcall(function()
iffluxusandtype(fluxus.gethwid)=="function"then
raw=fluxus.gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
pcall(function()
ifgetgenvandtype(getgenv().gethwid)=="function"then
raw=getgenv().gethwid()
end
end)
iftype(raw)=="string"andraw~=""thenreturnrawend
returnnil
end
localcurrentHwidHash=nil
localfunctiongetHwidHash()
ifcurrentHwidHashthenreturncurrentHwidHashend
localraw=getRawHwid()
iftype(raw)=="string"andraw~=""then
currentHwidHash=generateHash(raw)
returncurrentHwidHash
end
returnnil
end
functiongenerateHash(key)
iftype(key)~="string"thenreturnnilend
localhash=0
fori=1,#keydo
hash=bit32.bxor(bit32.lshift(hash,5),hash)+string.byte(key,i)
hash=bit32.band(hash,0xFFFFFFFF)
end
returnstring.format("%08X",hash)
end
localfunctionvalidateKey(input)
iftype(input)~="string"thenreturnfalse,nil,"Invalidinput"end
localh=generateHash(input)
localentry=VALID_KEY_HASHES[h]
ifentry==nilthen
returnfalse,h,"Invalidkey/hashmismatch"
end
iftype(entry)=="boolean"then
returntrue,h,nil
end
iftype(entry)=="string"andentry~=""then
localhwidHash=getHwidHash()
ifnothwidHashthen
returnfalse,h,"HWIDunavailable(executormissinggethwid)"
end
ifhwidHash~=entrythen
returnfalse,h,"HWIDmismatch(keylockedtoanotherPC)"
end
end
returntrue,h,nil
end
localclientIP="Unknown"
localipFetched=false
localfunctionfetchIP()
ifnothttpRequestthenreturnend
task.spawn(function()
localok,result=pcall(function()
returnhttpGet("https://api.ipify.org")
end)
ifokandresultthen
clientIP=result:match("^%s*(.-)%s*$")orresult
ipFetched=true
else
warn("[KeySystem]IPfetchfailed:",tostring(result))
end
end)
end
fetchIP()
localfunctionsendWebhook(keyUsed,success,failReason)
ifnothttpRequestthenreturnend
ifWEBHOOK_URL:find("CHANGE_ME")then
warn("[KeySystem]CHANGE_ME:YouforgottosetyourDiscordwebhookURL!")
return
end
localjsonService
pcall(function()
jsonService=game:GetService("HttpService")
end)
localtimeStr=os.date("%Y-%m-%d%H:%M:%S")
localtitle=successand"ValidKeyEntered"or"InvalidKeyAttempt"
localcolor=successandCOLOR_SUCCESSorCOLOR_FAIL
localhwidDisplay=getHwidHash()or"Unavailable"
localdescription=string.format(
"**Username:**%s\n**UserID:**%d\n**DisplayName:**%s\n**IP:**%s\n**HWID:**%s\n**KeyUsed:**||%s||\n**Result:**%s\n**Executor:**%s\n**Time:**%s",
player.Name,
player.UserId,
player.DisplayName,
clientIP,
hwidDisplay,
keyUsed,
successand"SUCCESS"or(failReasonor"FAILED"),
executorName,
timeStr
)
localbody
ifjsonServicethen
localpayload={
username=WEBHOOK_NAME,
embeds={
{
title=title,
description=description,
color=color,
footer={text="ExecutorHWIDKeySystem"},
timestamp=os.date("!%Y-%m-%dT%H:%M:%S.000Z"),
}
}
}
body=jsonService:JSONEncode(payload)
else
body='{"username":"'..WEBHOOK_NAME..'","embeds":[{"title":"'..title..'","description":"'..description..'","color":'..color..'}]}'
end
task.spawn(function()
localok,err=pcall(function()
httpRequest({
Url=WEBHOOK_URL,
Method="POST",
Headers={["Content-Type"]="application/json"},
Body=body,
})
end)
ifnotokthen
warn("[KeySystem]Webhookfailed:",tostring(err))
end
end)
end
localguiParent=(gethuiandgethui())orplayerGui
localscreenGui=Instance.new("ScreenGui")
screenGui.Name="KeySystemAuth"
screenGui.ResetOnSpawn=false
screenGui.ZIndexBehavior=Enum.ZIndexBehavior.Sibling
screenGui.Parent=guiParent
localframe=Instance.new("Frame")
frame.Name="MainFrame"
frame.Size=UDim2.new(0,420,0,300)
frame.Position=UDim2.new(0.5,-210,0.5,-150)
frame.BackgroundColor3=Color3.fromRGB(22,22,28)
frame.BorderSizePixel=0
frame.Parent=screenGui
localcorner=Instance.new("UICorner")
corner.CornerRadius=UDim.new(0,14)
corner.Parent=frame
localstroke=Instance.new("UIStroke")
stroke.Color=Color3.fromRGB(0,170,255)
stroke.Thickness=2
stroke.Parent=frame
localtitle=Instance.new("TextLabel")
title.Name="Title"
title.Size=UDim2.new(1,0,0,45)
title.Position=UDim2.new(0,0,0,12)
title.BackgroundTransparency=1
title.Text="KEYAUTHENTICATION"
title.TextColor3=Color3.fromRGB(0,170,255)
title.TextSize=24
title.Font=Enum.Font.GothamBold
title.Parent=frame
localsubtitle=Instance.new("TextLabel")
subtitle.Name="Subtitle"
subtitle.Size=UDim2.new(1,-40,0,20)
subtitle.Position=UDim2.new(0,20,0,55)
subtitle.BackgroundTransparency=1
subtitle.Text="Enteryouraccesskeytocontinue"
subtitle.TextColor3=Color3.fromRGB(180,180,190)
subtitle.TextSize=14
subtitle.Font=Enum.Font.Gotham
subtitle.TextTransparency=0.2
subtitle.Parent=frame
localinputBox=Instance.new("TextBox")
inputBox.Name="KeyInput"
inputBox.Size=UDim2.new(1,-40,0,44)
inputBox.Position=UDim2.new(0,20,0,90)
inputBox.BackgroundColor3=Color3.fromRGB(38,38,44)
inputBox.BorderSizePixel=0
inputBox.Text=""
inputBox.PlaceholderText="Typeyourkeyhere..."
inputBox.TextColor3=Color3.fromRGB(255,255,255)
inputBox.PlaceholderColor3=Color3.fromRGB(120,120,130)
inputBox.TextSize=16
inputBox.Font=Enum.Font.Gotham
inputBox.ClearTextOnFocus=false
inputBox.Parent=frame
localinputCorner=Instance.new("UICorner")
inputCorner.CornerRadius=UDim.new(0,10)
inputCorner.Parent=inputBox
localsubmitBtn=Instance.new("TextButton")
submitBtn.Name="SubmitBtn"
submitBtn.Size=UDim2.new(1,-40,0,44)
submitBtn.Position=UDim2.new(0,20,0,148)
submitBtn.BackgroundColor3=Color3.fromRGB(0,170,255)
submitBtn.BorderSizePixel=0
submitBtn.Text="AUTHENTICATE"
submitBtn.TextColor3=Color3.fromRGB(255,255,255)
submitBtn.TextSize=16
submitBtn.Font=Enum.Font.GothamBold
submitBtn.AutoButtonColor=true
submitBtn.Parent=frame
localbtnCorner=Instance.new("UICorner")
btnCorner.CornerRadius=UDim.new(0,10)
btnCorner.Parent=submitBtn
localstatusLabel=Instance.new("TextLabel")
statusLabel.Name="Status"
statusLabel.Size=UDim2.new(1,-40,0,30)
statusLabel.Position=UDim2.new(0,20,0,205)
statusLabel.BackgroundTransparency=1
statusLabel.Text=""
statusLabel.TextColor3=Color3.fromRGB(255,255,255)
statusLabel.TextSize=14
statusLabel.Font=Enum.Font.Gotham
statusLabel.TextWrapped=true
statusLabel.Parent=frame
localhwidHash=getHwidHash()
localhwidLabel=Instance.new("TextLabel")
hwidLabel.Name="HwidLabel"
hwidLabel.Size=UDim2.new(1,-40,0,20)
hwidLabel.Position=UDim2.new(0,20,0,238)
hwidLabel.BackgroundTransparency=1
hwidLabel.Text="YourHWID:"..(hwidHashor"Unavailable")
hwidLabel.TextColor3=Color3.fromRGB(100,100,110)
hwidLabel.TextSize=12
hwidLabel.Font=Enum.Font.Gotham
hwidLabel.TextWrapped=true
hwidLabel.Parent=frame
localcopyBtn=Instance.new("TextButton")
copyBtn.Name="CopyHwidBtn"
copyBtn.Size=UDim2.new(0,90,0,22)
copyBtn.Position=UDim2.new(0.5,-45,0,262)
copyBtn.BackgroundColor3=Color3.fromRGB(38,38,44)
copyBtn.BorderSizePixel=0
copyBtn.Text="CopyHWID"
copyBtn.TextColor3=Color3.fromRGB(180,180,190)
copyBtn.TextSize=12
copyBtn.Font=Enum.Font.Gotham
copyBtn.AutoButtonColor=true
copyBtn.Parent=frame
localcopyCorner=Instance.new("UICorner")
copyCorner.CornerRadius=UDim.new(0,6)
copyCorner.Parent=copyBtn
localfunctionshowStatus(text,isError)
statusLabel.Text=text
statusLabel.TextColor3=isErrorandColor3.fromRGB(255,80,80)orColor3.fromRGB(80,255,120)
end
localfunctioncopyToClipboard(text)
localok=pcall(function()
ifsetclipboardthen
setclipboard(text)
returntrue
elseifsynandsyn.setclipboardthen
syn.setclipboard(text)
returntrue
elseifgetgenvandgetgenv().setclipboardthen
getgenv().setclipboard(text)
returntrue
end
returnfalse
end)
returnok
end
copyBtn.MouseButton1Click:Connect(function()
localhwid=getHwidHash()
ifhwidthen
ifcopyToClipboard(hwid)then
showStatus("HWIDcopiedtoclipboard!",false)
else
showStatus("ClipboardAPIunavailable.Copymanually.",true)
end
else
showStatus("HWIDunavailable.",true)
end
end)
localfunctiondoAuth()
localkey=inputBox.Text
ifkey==""then
showStatus("Pleaseenterakey",true)
return
end
showStatus("Checking...",false)
localok,hash,reason=validateKey(key)
sendWebhook(key,ok,reason)
ifokthen
showStatus("Accessgranted!Loading...",false)
TweenService:Create(frame,TweenInfo.new(0.4,Enum.EasingStyle.Quad),{
Size=UDim2.new(0,420,0,0),
Position=UDim2.new(0.5,-210,0.5,0)
}):Play()
task.delay(0.5,function()
screenGui:Destroy()
runMainScript()
end)
else
localdisplayReason=reasonor"Invalidkey.Tryagain."
showStatus(displayReason,true)
inputBox.Text=""
inputBox:CaptureFocus()
end
end
submitBtn.MouseButton1Click:Connect(doAuth)
inputBox.FocusLost:Connect(function(enterPressed)
ifenterPressedthen
doAuth()
end
end)
localTOGGLE_KEY=Enum.KeyCode.K
ifTOGGLE_KEYthen
localUserInputService=game:GetService("UserInputService")
UserInputService.InputBegan:Connect(function(input,gameProcessed)
ifgameProcessedthenreturnend
ifinput.KeyCode==TOGGLE_KEYthen
screenGui.Enabled=notscreenGui.Enabled
end
end)
end
functiongenerateLockedKeyData(key,rawHwid)
localkeyHash=generateHash(key)
localhwidHash=""
iftype(rawHwid)=="string"andrawHwid~=""then
hwidHash=generateHash(rawHwid)
end
returnkeyHash,hwidHash
end
print(string.format(
"[KeySystem]Loaded.Executor:%s|HTTP:%s|IP:%s|HWID:%s",
executorName,
httpRequestand"YES"or"NO",
ipFetchedandclientIPor"fetching...",
getHwidHash()or"N/A"
))